[[agents]]
name = "Opencode"
website = "https://opencode.ai/"
repo = "https://github.com/sst/opencode"
open_source = true
summary = "Open source terminal-based coding agent with multi-provider LLM support."
detail = "Opencode supports 75+ LLM providers and integrates with IDEs including Cursor and VS Code, enabling flexible model subscriptions for terminal-based development workflows."
category = "Open source"

[[apps]]
name = "Kiro"
website = "https://kiro.dev/"
repo = ""
open_source = false
summary = "AI-powered IDE with spec-driven development and autonomous task execution."
detail = "Kiro transforms prompts into structured requirements and implementation tasks, supporting multimodal inputs and agent hooks for automated background workflows with Claude Sonnet integration."
category = "Commercial"
hot = true

[[interfaces]]
name = "claude-frontend"
website = ""
repo = "https://github.com/tobias-schuemann/claude-frontend"
open_source = true
summary = "Visual interface for AI-powered code modifications with Claude CLI."
detail = "claude-frontend provides a browser widget that allows developers to select webpage elements and send them to Claude for instant code modifications, supporting multiple frameworks including Next.js, Vite, React, and Vue in local development environments."
category = "Open source"

[[interfaces]]
name = "Claudia"
website = "https://claudiacode.com/"
repo = "https://github.com/getAsterisk/claudia"
open_source = true
summary = "Desktop GUI and toolkit for Claude Code with session management and custom agent creation."
detail = "Claudia provides a comprehensive desktop interface for Claude Code, offering project and session management, usage analytics, custom AI agent creation, and MCP server management with secure process isolation and local data storage."
category = "Open source"

[[interfaces]]
name = "Happy"
website = "https://happy.engineering/"
repo = "https://github.com/slopus/happy"
open_source = true
summary = "Mobile client for Claude Code with remote access and cross-device synchronization."
detail = "Happy enables developers to control Claude Code sessions remotely via mobile and web apps, providing push notifications, instant device switching, and end-to-end encrypted code transmission across iOS, Android, and web platforms."
category = "Commercial"

[[tools]]
name = "Archon"
website = "https://github.com/coleam00/Archon"
repo = "https://github.com/coleam00/Archon"
open_source = true
summary = "MCP server and knowledge management platform for AI coding assistants."
detail = "Archon provides custom knowledge bases with web crawling, vector search, and task management capabilities, supporting multiple LLMs and offering 10 MCP tools for enhanced RAG queries and collaborative development workflows."
category = "Memory"

[[tools]]
name = "cco"
website = ""
repo = "https://github.com/nikvdp/cco"
open_source = true
summary = "Protective wrapper for Claude Code with zero-config sandboxed execution."
detail = "cco provides automatic sandboxing for Claude Code using native OS tools or Docker fallback, enabling secure isolated interactions while maintaining seamless user experience and preserving project context across platforms."
category = "Security"

[[tools]]
name = "Kratos MCP"
website = ""
repo = "https://github.com/ceorkm/kratos-mcp"
open_source = true
summary = "Memory system MCP server for AI coding tools with 95.8% context accuracy."
detail = "Kratos MCP provides persistent memory for AI coding tools using a Four Pillars Framework with SQLite storage, ensuring AI maintains project context across sessions with sub-10ms retrieval times and automatic project isolation."
category = "Memory"

[[tools]]
name = "Shotgun App"
website = ""
repo = "https://github.com/glebkudr/shotgun_code"
open_source = true
summary = "Desktop tool for preparing comprehensive project context for AI coding assistants."
detail = "Shotgun App enables one-click generation of structured project payloads for LLM interactions, allowing selective file exclusion and supporting whole-repository analysis and modification workflows with ChatGPT, Gemini, and other AI assistants."
category = "Memory"

[[tools]]
name = "Task Master"
website = "https://www.task-master.dev/"
repo = ""
open_source = true
summary = "AI-powered task management system for coding workflows with MCP integration."
detail = "Task Master breaks down complex projects into manageable tasks, integrates with editors like Cursor and VS Code through MCP, and supports multiple AI providers to enhance development productivity without requiring API keys for Claude Code CLI usage."
category = "Memory"

[categories]
tools = ["Memory", "Security"]