[[agents]]
name = "Gemini CLI"
website = "https://google-gemini.github.io/gemini-cli/"
repo = "https://github.com/google-gemini/gemini-cli"
open_source = true
summary = "Open source terminal-based AI agent with Gemini 2.5 Pro and multimodal capabilities."
detail = "Gemini CLI brings Google's Gemini AI directly to the terminal with code generation, Google Search integration, file operations, and 1M token context window. Supports multiple authentication methods and offers extensible architecture for developer workflows."
category = "Open source"

[[agents]]
name = "Kilo Code"
website = "https://kilocode.ai/"
repo = "https://github.com/Kilo-Org/kilocode"
open_source = true
summary = "Open source VS Code AI coding agent with 400+ model support and multi-mode development assistance."
detail = "Kilo Code provides multiple agent modes (Orchestrator, Architect, Code, Debug) with automatic context searching, memory bank for project retention, and hallucination-free code generation. Supports 400+ AI models via OpenRouter without requiring API keys and includes browser automation capabilities."
category = "Open source"

[[agents]]
name = "OpenAI Codex"
website = "https://chatgpt.com/codex"
repo = ""
open_source = false
summary = "Cloud-based autonomous coding agent with multi-task execution and isolated environments."
detail = "OpenAI Codex operates in secure cloud sandboxes to handle multiple software engineering tasks simultaneously, including writing features, fixing bugs, and running tests, with 75% accuracy and support for ChatGPT Plus/Pro subscriptions."

[[agents]]
name = "Cline"
website = "https://cline.bot/"
repo = "https://github.com/cline/cline"
open_source = true
summary = "Open source AI coding agent for VS Code with autonomous capabilities and multi-model support."
detail = "Cline operates as a VS Code extension with autonomous file editing, terminal command execution, and browser automation capabilities. Features client-side architecture for security, supports multiple AI providers including Claude and Gemini, and offers transparent AI decision-making with human approval workflows."
category = "Open source"

[[agents]]
name = "Claude Code"
website = "https://www.anthropic.com/claude-code"
repo = ""
open_source = false
summary = "AI-powered terminal coding assistant with deep codebase understanding and multi-file coordination."
detail = "Claude Code embeds Claude Opus 4.1 directly in developers' terminals, providing agentic search across entire codebases, coordinated multi-file changes, and direct command execution in development environments with integrations for VS Code, JetBrains IDEs, GitHub, and enterprise tools."
hot = true

[[agents]]
name = "Devin"
website = "https://devin.ai/"
repo = ""
open_source = false
summary = "Autonomous AI software engineer that completes complex engineering tasks across codebases."
detail = "Devin handles code migration, refactoring, bug fixes, and development tasks with autonomous testing and PR creation, integrating with GitHub, Slack, Jira, and other platforms while learning from examples to improve performance over time."

[[agents]]
name = "Opencode"
website = "https://opencode.ai/"
repo = "https://github.com/sst/opencode"
open_source = true
summary = "Open source terminal-based coding agent with multi-provider LLM support."
detail = "Opencode supports 75+ LLM providers and integrates with IDEs including Cursor and VS Code, enabling flexible model subscriptions for terminal-based development workflows."

[[agents]]
name = "OpenHands"
website = "https://www.all-hands.dev/"
repo = "https://github.com/All-Hands-AI/OpenHands"
open_source = true
summary = "Open source AI software development agent platform with autonomous coding capabilities."
detail = "OpenHands enables AI agents to perform developer tasks autonomously including code modification, terminal commands, web browsing, and API calls. Supports multiple LLM providers with recommended Claude Sonnet 4 integration and offers both GUI and CLI interfaces for flexible development workflows."
category = "Open source"

[[agents]]
name = "OpenAI Codex CLI"
website = ""
repo = "https://github.com/openai/codex"
open_source = true
summary = "Experimental terminal-based coding agent with configurable sandbox modes."
detail = "Provides AI-powered code generation, refactoring, testing, and security scanning capabilities through both OpenAI and open-source models, with safety features including configurable sandbox execution to prevent unrestricted file access."

[[agents]]
name = "Qwen Code"
website = ""
repo = "https://github.com/QwenLM/qwen-code"
open_source = true
summary = "AI coding assistant CLI for exploring, developing, and automating software workflows."
detail = "Qwen Code is an intelligent command-line tool that helps developers understand, refactor, and generate code using advanced AI models. It provides workflow automation, code analysis, and supports multiple authentication methods across different regional providers."

[[agents]]
name = "Zed"
website = "https://zed.dev/"
repo = "https://github.com/zed-industries/zed"
open_source = true
summary = "High-performance collaborative code editor with AI-powered agentic editing capabilities."
detail = "Zed is a next-generation code editor built in Rust that enables fluent collaboration between humans and AI. Features native AI integration for code generation and transformation with upcoming LLM support, multiplayer editing, and custom language models for edit prediction."
category = "Open source"

[[apps]]
name = "Kiro"
website = "https://kiro.dev/"
repo = ""
open_source = false
summary = "AI-powered IDE with spec-driven development and autonomous task execution."
detail = "Kiro transforms prompts into structured requirements and implementation tasks, supporting multimodal inputs and agent hooks for automated background workflows with Claude Sonnet integration."
hot = true

[[apps]]
name = "v0"
website = "https://v0.app/"
repo = ""
open_source = false
summary = "AI-powered interface builder that generates React applications from text prompts and designs."
detail = "v0 converts natural language descriptions into full-stack applications with UI, content, backend, and logic. Features agentic capabilities for research and planning, generates code using Next.js, React, and Tailwind CSS, and integrates with GitHub and Vercel for seamless deployment."

[[interfaces]]
name = "claude-frontend"
website = ""
repo = "https://github.com/tobias-schuemann/claude-frontend"
open_source = true
summary = "Visual interface for AI-powered code modifications with Claude CLI."
detail = "claude-frontend provides a browser widget that allows developers to select webpage elements and send them to Claude for instant code modifications, supporting multiple frameworks including Next.js, Vite, React, and Vue in local development environments."

[[interfaces]]
name = "Claudia"
website = "https://claudiacode.com/"
repo = "https://github.com/getAsterisk/claudia"
open_source = true
summary = "Desktop GUI for Claude Code with session management and custom agent creation."
detail = "Claudia provides a visual command center for Claude Code featuring project browsers, session history tracking, custom AI agents with background execution, usage analytics, and process isolation for secure AI-assisted development workflows."

[[interfaces]]
name = "Agentrooms"
website = ""
repo = "https://github.com/baryhuang/claude-code-by-agents"
open_source = true
summary = "Multi-agent workspace for collaborative development with Claude CLI."
detail = "Agentrooms provides desktop and web interfaces for coordinating specialized AI agents in collaborative software development workflows, enabling task routing via @agent-name mentions, automatic decomposition, and management of complex multi-agent projects using Claude CLI as the underlying engine."


[[agents]]
name = "Cursor"
website = "https://cursor.com"
repo = ""
open_source = false
summary = "AI-powered code editor with predictive tab completion and natural language code editing."
detail = "Cursor is an AI-enhanced code editor that provides intelligent tab completion, codebase understanding, and natural language code modification capabilities. Imports VSCode extensions and themes while offering seamless AI integration for enhanced developer productivity."

[[interfaces]]
name = "Claude Code UI"
website = "https://claudecodeui.siteboon.ai/"
repo = "https://github.com/siteboon/claudecodeui"
open_source = true
summary = "Web and mobile interface for Claude Code with responsive design and Git integration."
detail = "Claude Code UI provides a multi-device interface with project browser, file explorer with syntax highlighting, session management, and security-focused tool permissions. Supports Claude Sonnet 4, Opus 4.1, and GPT-5 models with React-based responsive design for desktop and mobile development workflows."

[[interfaces]]
name = "Happy"
website = "https://happy.engineering/"
repo = "https://github.com/slopus/happy"
open_source = true
summary = "Mobile client for Claude Code with remote access and cross-device synchronization."
detail = "Happy enables developers to control Claude Code sessions remotely via mobile and web apps, providing push notifications, instant device switching, and end-to-end encrypted code transmission across iOS, Android, and web platforms."

[[tools]]
name = "Archon"
website = "https://github.com/coleam00/Archon"
repo = "https://github.com/coleam00/Archon"
open_source = true
summary = "MCP server and knowledge management platform for AI coding assistants."
detail = "Archon provides custom knowledge bases with web crawling, vector search, and task management capabilities, supporting multiple LLMs and offering 10 MCP tools for enhanced RAG queries and collaborative development workflows."
category = "Memory"

[[tools]]
name = "cco"
website = ""
repo = "https://github.com/nikvdp/cco"
open_source = true
summary = "Protective wrapper for Claude Code with zero-config sandboxed execution."
detail = "cco provides automatic sandboxing for Claude Code using native OS tools or Docker fallback, enabling secure isolated interactions while maintaining seamless user experience and preserving project context across platforms."
category = "Security"

[[tools]]
name = "Kratos MCP"
website = ""
repo = "https://github.com/ceorkm/kratos-mcp"
open_source = true
summary = "Memory system MCP server for AI coding tools with 95.8% context accuracy."
detail = "Kratos MCP provides persistent memory for AI coding tools using a Four Pillars Framework with SQLite storage, ensuring AI maintains project context across sessions with sub-10ms retrieval times and automatic project isolation."
category = "Memory"

[[tools]]
name = "Shotgun App"
website = ""
repo = "https://github.com/glebkudr/shotgun_code"
open_source = true
summary = "Desktop tool for preparing comprehensive project context for AI coding assistants."
detail = "Shotgun App enables one-click generation of structured project payloads for LLM interactions, allowing selective file exclusion and supporting whole-repository analysis and modification workflows with ChatGPT, Gemini, and other AI assistants."
category = "Codebase understanding"

[[tools]]
name = "playwright-mcp"
website = ""
repo = "https://github.com/microsoft/playwright-mcp"
open_source = true
summary = "MCP server providing browser automation capabilities using Playwright's accessibility tree."
detail = "playwright-mcp enables LLMs to interact with web pages through structured accessibility snapshots rather than pixel-based input, offering deterministic browser automation with clicking, typing, navigation, and screenshot tools for precise web interactions."
category = "Agent feedback"
hot = true

[[tools]]
name = "Task Master"
website = "https://www.task-master.dev/"
repo = ""
open_source = true
summary = "AI-powered task management system for coding workflows with MCP integration."
detail = "Task Master breaks down complex projects into manageable tasks, integrates with editors like Cursor and VS Code through MCP, and supports multiple AI providers to enhance development productivity without requiring API keys for Claude Code CLI usage."
category = "Task management"

[[workflows]]
name = "BMAD-METHOD"
website = ""
repo = "https://github.com/bmad-code-org/BMAD-METHOD"
open_source = true
summary = "AI-driven agile development framework with specialized agent orchestration and context engineering."
detail = "BMAD-METHOD combines agentic planning with context-engineered development, using specialized AI agents (Analyst, Product Manager, Architect, Scrum Master) to create detailed PRDs and hyper-detailed development stories that embed full implementation context and architectural guidance directly in story files."

[categories]
tools = ["Memory", "Task management", "Codebase understanding", "Security", "Other tools", "Agent feedback"]
