name: Auto Close External PRs

on:
  pull_request:
    types: [opened]

jobs:
  check-membership:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Check if author is a member
        id: check-member
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: membership } = await github.rest.orgs.getMembershipForUser({
                org: context.repo.owner,
                username: context.payload.pull_request.user.login
              });
              return membership.state === 'active';
            } catch (error) {
              // If we get a 404 or any other error, assume they're not a member
              if (error.status === 404) {
                return false;
              }
              // For public repos without an org, check if they're a collaborator
              try {
                const { data: collaboration } = await github.rest.repos.getCollaboratorPermissionLevel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  username: context.payload.pull_request.user.login
                });
                return ['admin', 'write', 'maintain'].includes(collaboration.permission);
              } catch (collabError) {
                return false;
              }
            }

      - name: Close PR if not a member
        if: steps.check-member.outputs.result == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is an automated message. To make a contribution to awesome-vibe-coding, please create a new issue instead of issuing a pull request.'
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: 'closed'
            });
